-- Why a worker is absent today
DO $$ BEGIN
  CREATE TYPE "AbsenceReason" AS ENUM ('INFORMED_LEAVE','LEAVE_WITHOUT_ASKING','NIGHT_SHIFT_REST','NOT_PICKING_UP','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE "LeaveDay" ADD COLUMN IF NOT EXISTS "reason" "AbsenceReason" NOT NULL DEFAULT 'INFORMED_LEAVE';
ALTER TABLE "LeaveDay" ADD COLUMN IF NOT EXISTS "note" TEXT;
